version: '3.3'
networks:
   kmetadbnet: null
services:
   postgres1:
      image: postgres:16
      networks:
      - kmetadbnet
      ports:
      - '5432'
      volumes:
      - postgresdata01:/var/lib/postgresql/data
      environment:
      - POSTGRES_DB=kmetadb
      - POSTGRES_USER=kmetadb
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data/pgdata
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
        interval: 1s
        timeout: 5s
        retries: 10
   kmetadb:
      depends_on:
        postgres1:
          condition: service_healthy
      image: com.github.eyefloaters/kmetadb:latest
      networks:
      - kmetadbnet
      ports:
      - 8080:8080
      env_file:
      - .env
      environment:
      - QUARKUS_DATASOURCE_DB_KIND=postgresql
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres1:5432/kmetadb
      - QUARKUS_DATASOURCE_USERNAME=kmetadb
      - QUARKUS_DATASOURCE_PASSWORD=password
volumes:
   postgresdata01: {}
