version: '3.3'
networks:
   kmetadbnet: null
services:
   kmetadb:
      image: com.github.eyefloaters/kmetadb:latest
      networks:
      - kmetadbnet
      ports:
      - 8080:8080
      env_file:
      - .env
      environment:
      - QUARKUS_DATASOURCE_DB_KIND=postgresql
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres1:5432/kmetadb
      - QUARKUS_DATASOURCE_USERNAME=kmetadb
      - QUARKUS_DATASOURCE_PASSWORD=password
   postgres1:
      image: postgres:16
      networks:
      - kmetadbnet
      ports:
      - '5432'
      volumes:
      - postgresdata01:/var/lib/postgresql/data
      environment:
      - POSTGRES_DB=kmetadb
      - POSTGRES_USER=kmetadb
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data/pgdata
volumes:
   postgresdata01: {}
